# Numpy

**Numpy** stands for **Numerical Python**

- It's working is mush more faster than working with Lists.

- In case of List, computer have to save the type of each element separatly.

- So, it becomes slow as compare to the array. Because, array is a data structure of contigeouse type. we need not to store data type for each element.

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [5]:
b = np.array((2,4,6,8,0))

In [7]:
print(a)
print(b)

[1 2 3 4 5]
[2 4 6 8 0]


In [10]:
# ndarray means 'n dimentional array'
print(type(a))

<class 'numpy.ndarray'>


In [21]:
c = np.array([2,3,4,5,6,9],dtype='f')
# We can specify data type separatly 

In [23]:
print(c.dtype)

float32


Several Properties of **Numpy array**

**ndim** is used to get the dimention of array

In [28]:
# del a
a = np.array([[1,2,3],[4,5,6]])

In [29]:
print(a.ndim)

2


In [31]:
print(a)

[[1 2 3]
 [4 5 6]]


In [33]:
print(a[1,2])

6


we have to store same dimention of sub arrays inside an array otherwise objection arose.

In [34]:
B = np.array([[1,2,3,-1],[2,4,5,9]])

In [37]:
B.ndim

2

In [39]:
print(B[0,3])

-1


In [48]:
C = np.array([[[1,2,3], [4,5,6], [0,0,-1]], [[-1,-2,-3], [-4,-5,-6], [0,0,1]]])

In [46]:
print(C.dtype)

int32


In [49]:
print(C.ndim)

3


In [52]:
print(C[1,1,2])

-6


**shape** module is used to get dimention of each array inside array.i.e.,

In [57]:
print(C.shape)
# It's mean: C array is containing 2 sub arrays; each sub array is further containing 3 arrays; further 
# each array is containing 3 elements in it
print(type(C.shape))

(2, 3, 3)
<class 'tuple'>


In [58]:
print(C.shape[2])

3


In [59]:
A = np.array([3])

In [61]:
print(A.ndim)

1


In [62]:
B = np.array(9)

In [64]:
print(B.ndim)

0


**size** module returns the number of total elements in an array

In [66]:
print(C.size)

18


**nbytes** is used to get memory used by array

In [67]:
print(C.nbytes)

72
